autoInstallPeers: true

onlyBuiltDependencies:
  - '@nestjs/core'
  - '@prisma/client'
  - '@prisma/engines'
  - '@scarf/scarf'
  - '@swc/core'
  - bcrypt
  - nx
  - prisma
  - sharp

strictPeerDependencies: false
